name: 'Auto Author Assign'

on:
  pull_request:
    branches:
      - main

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign
        with:
          repo-token: "${{ secrets.NPM_AUTH_TOKEN }}"